plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: minima
title: .edu Community Mentorship
description: A site about the edu community mentorship program
header_pages:
  - README.md
  - FAQ.md
  - guide.md
